plugins:
  - jekyll-relative-links
title: My World
description: >- # this means to ignore newlines until "baseurl:"
  My Personal Blog
relative_links:
  enabled: true
  collections: true
include:
  - TEST.md
  - index.md
